<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Confirmation Error</title>
</head>
<body>
<h1>Error Confirming Account</h1>
<p>The confirmation code is invalid or the account is already confirmed.</p>
</body>
</html>
