<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Confirmation</title>
    <link rel="stylesheet" href="/static/css/confirmation.css">
</head>
<body>
<div class="container">
    <h1>Email Confirmation</h1>
    <p>A confirmation email has been sent to you.</p>
    <p>Please follow the instructions in the email to confirm your email address.</p>
</div>
</body>
</html>