<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forgot Password Success</title>
    <link rel="stylesheet" href="/static/css/password.css">
</head>
<body>
<div class="container">
    <div class="container">
        <div class="logo-container">
            <img src="/static/images/logo.png" alt="SpringTube Logo">
        </div>
        <form action="/forgotPasswordSuccess" method="post">

            <h1>Forgot Password Success</h1>
            <p>An email has been sent with instructions to reset your password.</p>
            <p>Please check your email inbox and follow the instructions provided.</p>
            <a href="/signIn" class="link">Return to Sign In</a>

        </form>
    </div>
</div>
</body>
</html>
