<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome To...</title>
    <link rel="stylesheet" href="/static/css/loading.css">
</head>
<body>
<div class="loading-container">
    <h1>SpringTube</h1>
    <img src="/static/images/logo.png" alt="SpringTube Logo" class="logo">
</div>
<script>
    setTimeout(function() {
        window.location.href = "/springtube";
    }, 2000);
</script>
</body>
</html>
