<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset Success</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="/static/css/password.css">
</head>
<body>
<div class="container">
    <div class="container">
        <div class="logo-container">
            <img src="/static/images/logo.png" alt="SpringTube Logo">
        </div>
        <form action="/resetPasswordSuccess" method="post">
            <h1>Password Reset Success</h1>
            <p>Your password has been successfully reset.</p>
            <a href="/springtube">Return to Home Page</a>
        </form>
    </div>
</div>
</body>
</html>
