<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thanks</title>
    <link rel="stylesheet" href="/static/css/epassword.css">
</head>
<body>
<div class="container">
  <div class="logo-container">
    <img src="/static/images/logo.png" alt="SpringTube Logo">
  </div>
    <div class="thank-you-container">
        <h1>Thank You for Your Message!</h1>
        <p>We have received your email and our team will review it and get back to you as soon as possible.</p>
        <p>Your feedback is important to us and helps us improve our services. If your inquiry is urgent, please use the telephone number listed on our contact page to talk to one of our staff members directly.</p>
        <p>Thank you once again for reaching out to us.</p>
        <a href="/">Return to Home</a>
    </div>
</div>
</body>
</html>